/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    kotlin("jvm") version "1.9.0"
}

group = "api"
version = "1.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { url = uri("https://repo.maven.apache.org/maven2") } // Ensures Maven Central is used
    maven { url = uri("https://aws.oss.sonatype.org/content/repositories/releases/") } // AWS Repository
}

dependencies {
    // AWS Lambda Core
    implementation("com.amazonaws:aws-lambda-java-core:1.2.1")
    
    // AWS Lambda Events for API Gateway
    implementation("com.amazonaws:aws-lambda-java-events:3.11.1")

    // AWS Lambda Java Runtime Interface Client (For AWS Lambda JVM support)
    implementation("com.amazonaws:aws-lambda-java-runtime-interface-client:2.1.1")

    // AWS SDK for DynamoDB (v2)
    implementation("software.amazon.awssdk:dynamodb:2.20.124")

    // AWS SDK BOM (ensures all AWS SDK dependencies use the same version)
    implementation(platform("software.amazon.awssdk:bom:2.20.124"))

    // AWS SDK for S3
    implementation("software.amazon.awssdk:s3:2.20.124")

    // Jackson for JSON serialization
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.0")

    // Logging
    implementation("org.slf4j:slf4j-api:2.0.7")
    implementation("org.slf4j:slf4j-simple:2.0.7")

    // Testing
    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.withType<Jar> {    
    from(*configurations.runtimeClasspath.get().filter { it.exists() }.map { zipTree(it) }.toTypedArray())
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}


tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
